version: '3.2'

services:
  redis:
    image: redis
    command: redis-server
    ports:
      - 6379:6379

  app:
    container_name: "url-shortener-nodejs"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/url-shortener
    ports:
      - "3333:3333"
    networks:
      - default

networks:
  default:
    driver: bridge
